secrets:
  - SUPABASE_DB_URL
  - STRIPE_SECRET_KEY
  - STRIPE_WEBHOOK_SECRET
  - NEXT_PUBLIC_STRIPE_PRICE_MONTHLY
  - NEXT_PUBLIC_STRIPE_PRICE_ANNUAL
  - ADMIN_API_KEY
  - OPENAI_API_KEY
  - OPENAI_PROJECT_ID
  - ABLY_API_KEY
  - ABLY_SERVER_API_KEY
  - NEXT_PUBLIC_SUPABASE_URL
  - NEXT_PUBLIC_SUPABASE_ANON_KEY
  - SUPABASE_SERVICE_ROLE_KEY


