name: 游 Buggrapport
description: Rapportera ett fel som p친verkar Skolapp
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: desc
    attributes:
      label: Beskrivning
      description: Kort om vad som 칛r fel och var det syns.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steg f칬r att 친terskapa
      placeholder: |
        1) G친 till ...
        2) Klicka p친 ...
        3) F칬rv칛ntat ...
        4) Faktiskt ...
    validations:
      required: true

  - type: input
    id: env
    attributes:
      label: Milj칬
      description: Ex. iOS/Android/Chrome/Edge + versionsinfo.
      placeholder: "t.ex. iOS 17, Safari; Chrome 126, macOS"
  - type: checkboxes
    id: impact
    attributes:
      label: P친verkan
      options:
        - label: Blockerande
        - label: P친verkar flera anv칛ndare
        - label: Bara kosmetiskt
