name: API Smoke

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  api-smoke:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: API: OpenAI
        run: npm run api:openai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}

      - name: API: Ably
        run: npm run api:ably
        env:
          ABLY_SERVER_API_KEY: ${{ secrets.ABLY_SERVER_API_KEY }}

      - name: API: Skolverket
        run: npm run api:skolverket