name: Backfill attempt_items

on:
  workflow_dispatch:
    inputs:
      supabase_db_url:
        description: "Postgres connection URL (service role). If empty, uses secrets.SUPABASE_DB_URL"
        required: false
      statement_timeout:
        description: "Statement timeout, e.g. 10min"
        required: false
        default: "10min"

jobs:
  run-backfill:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Resolve DB URL
        id: cfg
        env:
          INPUT_URL: ${{ github.event.inputs.supabase_db_url }}
          SECRET_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          if [ -n "$INPUT_URL" ]; then
            echo "db_url=$INPUT_URL" >> $GITHUB_OUTPUT
          elif [ -n "$SECRET_URL" ]; then
            echo "db_url=$SECRET_URL" >> $GITHUB_OUTPUT
          else
            echo "::error::Missing DB URL. Provide workflow input supabase_db_url or set secrets.SUPABASE_DB_URL" && exit 1
          fi

      - name: Run backfill script
        env:
          PGCONNECT_TIMEOUT: 10
          STATEMENT_TIMEOUT: ${{ github.event.inputs.statement_timeout }}
        run: |
          DB_URL='${{ steps.cfg.outputs.db_url }}'
          echo "Connecting to Postgres..."
          # Replace statement timeout in-flight if provided
          # Run ops SQL; psql does not inherit local timeouts from env, they are in the SQL file
          psql "$DB_URL" -v ON_ERROR_STOP=1 -f supabase/ops/backfill_attempt_items.sql


