name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Ser till att nya körningar av samma PR ersätter gamla
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Next.js build
    runs-on: ubuntu-latest

    env:
      NEXT_TELEMETRY_DISABLED: 1
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # tips: pinna till SHA om ni vill (säkerhetspolicy)

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Cache för Next.js kompilationscache
      - name: Cache Next.js build
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.{js,jsx,ts,tsx}') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build
