name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  Lint & Type Check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4 pinned
      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4 pinned
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Lint (0 warnings)
        run: npm run lint -- --max-warnings=0
      - name: Type-check
        run: npm run type-check

  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Setup Node
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 20
          cache: npm
      - name: Restore Next.js cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4 pinned
        with:
          path: |
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]sx?', '**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
