name: Health Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  health-checks:
    name: Health Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Health Check - OpenAI
        run: npm run health:openai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
        continue-on-error: true
        id: openai-health
      
      - name: Health Check - Ably
        run: npm run health:ably
        env:
          ABLY_SERVER_API_KEY: ${{ secrets.ABLY_SERVER_API_KEY }}
        continue-on-error: true
        id: ably-health
      
      - name: Save health check results
        run: |
          mkdir -p reports
          echo "# Health Check Results" > reports/health-check.md
          echo "" >> reports/health-check.md
          echo "Generated: $(date)" >> reports/health-check.md
          echo "" >> reports/health-check.md
          
          if [ "${{ steps.openai-health.outcome }}" == "success" ]; then
            echo "✅ OpenAI: OK" >> reports/health-check.md
          else
            echo "❌ OpenAI: Failed" >> reports/health-check.md
          fi
          
          if [ "${{ steps.ably-health.outcome }}" == "success" ]; then
            echo "✅ Ably: OK" >> reports/health-check.md
          else
            echo "❌ Ably: Failed" >> reports/health-check.md
          fi
          
          cat reports/health-check.md
      
      - name: Upload health check results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: health-check-results
          path: reports/health-check.md
          retention-days: 7