name: QA suite

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: ['**']
  workflow_dispatch: {}

permissions:
  contents: read

env:
  CI: "true"
  NEXT_TELEMETRY_DISABLED: "1"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

jobs:
  lint_typecheck:
    name: QA suite / Lint & Type Check (pull_request)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # TypeScript (strikt, ingen emit)
      - run: |
          if npm run | grep -q "type-check"; then
            npm run type-check
          else
            npx tsc --noEmit
          fi
      # ESLint v9 flat (0 warnings policy)
      - run: |
          if npm run | grep -q "lint"; then
            npm run lint -- --max-warnings=0
          else
            npx eslint . --max-warnings=0
          fi

  security_scan:
    name: QA suite / Security Scan (pull_request)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # Snabb baseline: audit – production deps
      - run: |
          npm audit --omit=dev || true
      # Valfritt repo-skript (körs om det finns)
      - run: |
          if [ -x scripts/security/scan.sh ]; then scripts/security/scan.sh; fi

  deprecated_deps:
    name: QA suite / Deprecated Dependencies Check (pull_request)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # Kör ditt script om det finns, annars en mild fallback
      - run: |
          if [ -x scripts/check-deprecated-packages.sh ]; then
            scripts/check-deprecated-packages.sh
          else
            echo "Fallback: listar installerade paket"
            npm ls --depth=0 || true
          fi
      - name: Upload report (optional)
        if: hashFiles('*.md','*.json','**/deprecated*.{md,json}') != ''
        uses: actions/upload-artifact@v4
        with:
          name: deprecated-report
          path: |
            **/deprecated*.md
            **/deprecated*.json
            deprecated*.md
            deprecated*.json
          retention-days: 30

  perf_budget:
    name: QA suite / Performance Budget Check (pull_request)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # Kör ditt budget-script om det finns, annars gör en snabb build + no-op
      - run: |
          if [ -x scripts/check-performance-budget.sh ]; then
            scripts/check-performance-budget.sh
          elif npm run | grep -q "analyze:ci"; then
            npm run analyze:ci
          else
            echo "No explicit performance budget script found. Doing a lean build for smoke."
            npm run build --if-present
          fi
      - name: Upload bundle/report (optional)
        if: hashFiles('**/lighthouse*.{json,html}','**/bundle*.{json,html}') != ''
        uses: actions/upload-artifact@v4
        with:
          name: performance-artifacts
          path: |
            **/lighthouse*.json
            **/lighthouse*.html
            **/bundle*.json
            **/bundle*.html
          retention-days: 30

  cross_browser_chromium:
    name: QA suite / Cross-browser Testing (chromium) (pull_request)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - name: Run Playwright (chromium)
        run: |
          if [ -d tests/e2e ] || [ -d e2e ] || npm run | grep -q "test:e2e"; then
            if npm run | grep -q "test:e2e"; then
              npm run test:e2e -- --project=chromium
            else
              npx playwright test --project=chromium --reporter=line
            fi
          else
            echo "No e2e tests found. Skipping…"
          fi

  cross_browser_firefox:
    name: QA suite / Cross-browser Testing (firefox) (pull_request)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps firefox
      - name: Run Playwright (firefox)
        run: |
          if [ -d tests/e2e ] || [ -d e2e ] || npm run | grep -q "test:e2e"; then
            if npm run | grep -q "test:e2e"; then
              npm run test:e2e -- --project=firefox
            else
              npx playwright test --project=firefox --reporter=line
            fi
          else
            echo "No e2e tests found. Skipping…"
          fi

  cross_browser_webkit:
    name: QA suite / Cross-browser Testing (webkit) (pull_request)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps webkit
      - name: Run Playwright (webkit)
        run: |
          if [ -d tests/e2e ] || [ -d e2e ] || npm run | grep -q "test:e2e"; then
            if npm run | grep -q "test:e2e"; then
              npm run test:e2e -- --project=webkit
            else
              npx playwright test --project=webkit --reporter=line
            fi
          else
            echo "No e2e tests found. Skipping…"
          fi

  swedish_language:
    name: QA suite / Swedish Language Validation (pull_request)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # Kör ditt UI-fokuserade språkvalideringsscript om det finns
      - run: |
        # kör Node-script om det finns
          if [ -f scripts/lang/check-swedish-language.mjs ]; then
            node scripts/lang/check-swedish-language.mjs
          elif [ -x scripts/check-swedish-language.sh ]; then
            scripts/check-swedish-language.sh
          else
            echo "No Swedish language validation script found. Skipping…"
          fi
      - name: Upload language reports (optional)
        if: hashFiles('**/language-report*.{md,json}') != ''
        uses: actions/upload-artifact@v4
        with:
          name: language-validation
          path: '**/language-report*.{md,json}'
          retention-days: 30
