name: QA / Visual Snapshots
on:
  pull_request:
    branches: [main]

jobs:
  visual-snapshots:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

      - name: Start application
        run: npm run start &
        env:
          NODE_ENV: production

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000 --timeout 60000

      - name: Run visual tests
        run: npx playwright test --project=chromium-desktop-light --project=chromium-mobile-light
        env:
          BASE_URL: http://localhost:3000
          TEST_TEACHER_EMAIL: ${{ secrets.TEST_TEACHER_EMAIL || 'teacher@test.skolapp.dev' }}
          TEST_TEACHER_PASSWORD: ${{ secrets.TEST_TEACHER_PASSWORD || 'testpassword123' }}
          TEST_STUDENT_EMAIL: ${{ secrets.TEST_STUDENT_EMAIL || 'student@test.skolapp.dev' }}
          TEST_STUDENT_PASSWORD: ${{ secrets.TEST_STUDENT_PASSWORD || 'testpassword123' }}

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-screenshots
          path: test-results/
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 7